name = "VKcurve"
uuid = "3aa97455-9fe4-4946-8fa7-967d4b754676"
authors = ["Jean Michel <jean.michel@imj-prg.fr>"]
version = "0.1.0"

[deps]
Chevie = "367f69f0-ca63-11e8-2372-438b29340c1b"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
Chevie = "0.1.2"
julia = "1.10"
Reexport = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
